baseURL: 'https://www.scutzch.com/'
languageCode: zh-cn # en-us Set language
title: Changhui blog

theme: 
  - PaperMod
# theme: ["hugo-video","PaperMod"] #与themes下的文件名一致

enableInlineShortcodes: true
enableEmoji: true

enableRobotsTXT: true
hasCJKLanguage: true

buildDraft: false
buildFuture: false
buildExpired: false

googleAnalytics: 

#Copyright: Changhui ZHANG
paginate: 15
summaryLength: 140

minify:
 disableXML: true

permalinks: #访问博客网址显示形式
 posts: "posts/:title/"

defaultContentLanguage: zh #en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

enableGitInfo: false

languages:
 zh:
 languageName: "English"
 weight: 1
 profileMode:
 enabled: true
 title: 追寻生命的自由
 subtitle: ""
 imageUrl: "images/logo2.jpg"
 imageTitle: "Changhui's profile image"
 imageWidth: 150
 imageHeight: 165
 buttons:
        - name:  知识
 url: posts/reading
        - name: ☀️生活
 url: posts/life
        - name:  ️技术
 url: posts/technology
        - name:   认知思维
 url: posts/mind 
        - name: ❤️爱情
 url: posts/love

 menu:
 main:
        - identifier: home
 name:   主页
 url: /
 weight: 100
        - identifier: search
 name:   搜索
 url: search
 weight: 2
 
        - identifier: posts
 name:   文章
 url: posts
 weight: 3
        - identifier: tags
 name:   标签
 url: tags
 weight: 15
        - identifier: archives
 name: ⏱️ 时间轴
 url: archives/
 weight: 20
        - identifier: about
 name:   ‍♂️ 关于
 url: about
 weight: 50r/> # - identifier: linksr/> #   name:   友链r/> #   url: linksr/> #   weight: 60

outputs:
 home:
    - HTML
    - RSS
    - JSON
frontmatter:
 lastmod:
    ["lastmod", ":git", "date", "publishDate"]
params:
 env: production # to enable google analytics, opengraph, twitter-cards and schema.
 description: "Changhui 个人博客, hugo Papermod 主题, 读书笔记, 张昌辉个人博客"
 author: Changhui Zhang

 defaultTheme: auto # defaultTheme: light or  dark
 disableThemeToggle: false
 DateFormat: "2006-01-02"
 ShowShareButtons: true
 ShowReadingTime: truer/> # disableSpecialistPost: true
 displayFullLangName: true
 ShowPostNavLinks: true
 ShowBreadCrumbs: true
 ShowCodeCopyButtons: true
 hideFooter: false # 隐藏页脚
 ShowWordCounts: true
 VisitCount: true
 ShowVisitCount: true
 ShowLastMod: true #显示文章更新时间



 ShowToc: true # 显示目录
 TocOpen: true # 自动展开目录
 comments: true

 socialIcons:
    - name: github
 url: "https://github.com/zch1996"
    - name: WeChat
 url: "images/wechat.jpg"
    - name: email
 url: "mailto:scutzch@gmail.com"

 label: #left corner logo
 text: "Changhui Blog"
 icon: "images/logo2.jpg"
 iconHeight: 35

 analytics:
 google:
 SiteVerificationTag: ""

 assets:
 favicon: "images/logo2.jpg"
 favicon16x16: "images/logo2.jpg"
 favicon32x32: "images/logo2.jpg"
 apple_touch_icon: "images/logo2.jpg"
 safari_pinned_tab: "images/logo2.jpg"

 cover:
 hidden: false # hide everything but not in structured data

 hiddenInList: false

 hiddenInSingle: false

 fuseOpts:
 isCaseSensitive: false
 shouldSort: true
 location: 0
 distance: 1000
 threshold: 0.4
 minMatchCharLength: 0
 keys: [ "title", "permalink", "summary", "content" ]

 StartYear: 2023
 FilingNo: 2002
 PublicSecurityIconLink: /images/beian.png
 PublicNetworkSecurity: 备案号：粤ICP备2023058935号-1

 Reward: true
 WechatPay: images/wechat_pay.jpg
/>
 # twikoo评论
 twikoo:
 version: 1.6.16 # 填写twikoo版本号
 id:  https://vercel-comment-repository.vercel.app# 填写自己的twikoo id
 region:  # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数，请看twikoo官方文档
taxonomies:
 category: categories
 tag: tags
 series: series

markup:
 goldmark:
 renderer:
 unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
 highlight:r/> # anchorLineNos: true
 codeFences: true
 guessSyntax: truer/> # lineNos: true
 noClasses: true
 tabWidth: 4
 style: monokair/> # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。r/> # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。r/> # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。r/> # lineNoStart：行号从编号几开始，一般从 1 开始。r/> # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.r/> # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.r/> # noClasses：使用 class 标签，而不是内嵌的内联样式



privacy:
 vimeo:
 disabled: false
 simple: true

 twitter:
 disabled: false
 enableDNT: true
 simple: true

 instagram:
 disabled: false
 simple: true

 youtube:
 disabled: false
 privacyEnhanced: true

services:
 instagram:
 disableInlineCSS: true
 twitter:
 disableInlineCSS: true